### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by cancan101** [canavandl/jupyterlab_sandbox#2]
Currently getting:
```
ValueError: "jupyterlab_iframe" is not a valid npm package
```

**Comment by canavandl** [comment]
Hi @cancan101 

I finally published to npm as ``jupyterlab_sandbox``. It's pretty rough but addresses my immediate use-case (loading/embedding bokeh apps as panels). If/when you try it out, please don't hesitate to open issues/enhancements.
